### Site Settings ###
title: Tomás Rawski
description: Argentinean artist. His work is about relationships. One's relationships with what surrounds us and the relationships between people. He is interested in analysing those ways of relating that in principle often go unnoticed because they are natural and everyday. The way we relate to each other determines how we relate to the outside world.
baseurl: "" # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository: # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme: rtomas/portfolYOU

### Plugins ###
plugins:

### Navbar Settings ###
nav_exclude: # The following paths are excluded from navbar
    - pages/tags.html
    - pages/404.html
    - pages/index.md

### Author Info ###
author:
    name: Tomás Rawski
    #  image             : https://i.imgur.com/uyDNQnn.jpg
    #behance           : your_username
    # dribbble          : your_username
    email: info at tomasrawski (.) com (.) ar
    #facebook          : your_username
    #github            : your_username
# gitlab            : your_username
# instagram         : tomas.rawski
# kaggle            : your_username
#linkedin          : your_username
#medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name

### Posts ###
permalink: /textos/:title

### Collections ###
collections:
    projects:
        output: true
        permalink: /projects/:name

### Analytics ###
analytics:
    enabled: true # Set true to enable analytics
    google:
        tracking_id: UA-175891-9

### Defaults for collections ###
defaults:
    - scope:
          path: ""
          type: "projects"
      values:
          layout: "page"
    - scope:
          path: ""
          type: "posts"
      values:
          comments: false

### Exclude from processing ###
exclude:
    - README.md
    - CONTRIBUTING.md
    - LICENSE
    - "*.log"
    - tmp/
    - vendor/
    - Gemfile
    - Gemfile.lock
